/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedCreateOrganizationRouteRouteImport } from './routes/(authenticated)/create-organization/route'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as authenticatedCreateOrganizationIndexRouteImport } from './routes/(authenticated)/create-organization/index'
import { Route as authPagesSignupIndexRouteImport } from './routes/(auth-pages)/signup/index'
import { Route as authPagesLoginIndexRouteImport } from './routes/(auth-pages)/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedCreateOrganizationRouteRoute =
  authenticatedCreateOrganizationRouteRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedCreateOrganizationIndexRoute =
  authenticatedCreateOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedCreateOrganizationRouteRoute,
  } as any)
const authPagesSignupIndexRoute = authPagesSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginIndexRoute = authPagesLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organization': typeof authenticatedCreateOrganizationRouteRouteWithChildren
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof authPagesLoginIndexRoute
  '/signup': typeof authPagesSignupIndexRoute
  '/create-organization/': typeof authenticatedCreateOrganizationIndexRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof authPagesLoginIndexRoute
  '/signup': typeof authPagesSignupIndexRoute
  '/create-organization': typeof authenticatedCreateOrganizationIndexRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/create-organization': typeof authenticatedCreateOrganizationRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth-pages)/login/': typeof authPagesLoginIndexRoute
  '/(auth-pages)/signup/': typeof authPagesSignupIndexRoute
  '/(authenticated)/create-organization/': typeof authenticatedCreateOrganizationIndexRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/dashboard'
    | '/api/auth/$'
    | '/login'
    | '/signup'
    | '/create-organization/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/login'
    | '/signup'
    | '/create-organization'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(authenticated)/create-organization'
    | '/(authenticated)/dashboard'
    | '/api/auth/$'
    | '/(auth-pages)/login/'
    | '/(auth-pages)/signup/'
    | '/(authenticated)/create-organization/'
    | '/(authenticated)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/create-organization': {
      id: '/(authenticated)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof authenticatedCreateOrganizationRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/create-organization/': {
      id: '/(authenticated)/create-organization/'
      path: '/'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof authenticatedCreateOrganizationIndexRouteImport
      parentRoute: typeof authenticatedCreateOrganizationRouteRoute
    }
    '/(auth-pages)/signup/': {
      id: '/(auth-pages)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupIndexRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login/': {
      id: '/(auth-pages)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginIndexRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginIndexRoute: typeof authPagesLoginIndexRoute
  authPagesSignupIndexRoute: typeof authPagesSignupIndexRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginIndexRoute: authPagesLoginIndexRoute,
  authPagesSignupIndexRoute: authPagesSignupIndexRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedCreateOrganizationRouteRouteChildren {
  authenticatedCreateOrganizationIndexRoute: typeof authenticatedCreateOrganizationIndexRoute
}

const authenticatedCreateOrganizationRouteRouteChildren: authenticatedCreateOrganizationRouteRouteChildren =
  {
    authenticatedCreateOrganizationIndexRoute:
      authenticatedCreateOrganizationIndexRoute,
  }

const authenticatedCreateOrganizationRouteRouteWithChildren =
  authenticatedCreateOrganizationRouteRoute._addFileChildren(
    authenticatedCreateOrganizationRouteRouteChildren,
  )

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedCreateOrganizationRouteRoute: typeof authenticatedCreateOrganizationRouteRouteWithChildren
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedCreateOrganizationRouteRoute:
    authenticatedCreateOrganizationRouteRouteWithChildren,
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
